### ISSUE TITLE
github_token() defunct

### ISSUE THREAD

**Issue by artxz** [natverse/natmanager#16]
Hi Sridhar and Greg, 

`natmanager::install('natverse')`  returns an error

Error: `github_token()` was deprecated in usethis 2.0.0 and is now defunct.
Call `gh::gh_token()` to retrieve a GitHub personal access token
Call `gh_token_help()` if you need help getting or configuring your token

**Comment by jefferis** [comment]
Thanks @artxz. @SridharJagannathan already fixed this in #15. Sri will try to get an updated version on CRAN soon.
