### ISSUE TITLE
github_token() deprecated in usethis 2.0.0

### ISSUE THREAD

**Issue by tatsuookubo** [natverse/natmanager#18]
Hi,

I recently uploaded R and all the packages and realized that natmanager::install gives me an error due to the change in how `usethis` manages GitHub token.

`natmanager::install("natverse")` gives me the following error (R 4.0.3; usethis 2.0.0; natmanager 0.4.6)
```
Error: `github_token()` was deprecated in usethis 2.0.0 and is now defunct.
Call `gh::gh_token()` to retrieve a GitHub personal access token
Call `gh_token_help()` if you need help getting or configuring your token
```
Thank you!
Tatsuo

**Comment by SridharJagannathan** [comment]
Hi @tatsuookubo ,
Currently we are in the process of updating the package on `cran`, you can see that this issue has already been solved in #15
For the timebeing you can use the install instructions on the readme which says `devtools::install_github('natverse/natmanager')`

**Comment by jefferis** [comment]
Thanks @SridharJagannathan. CRAN are back from their holiday now although they must have a large backlog. Could you submit an update?

**Comment by SridharJagannathan** [comment]
@jefferis I have already submitted an update, I think it is in `pretest` stage now.

**Comment by tatsuookubo** [comment]
Hi Sridhar and Greg,
Thank you for your help and apologies for the duplicate post (I was only searching in the open issues). This fixed my problem.

Best,
Tatsuo
