### ISSUE TITLE
CRAN build fails for natmanager v0.4.8

### ISSUE THREAD

**Issue by SridharJagannathan** [natverse/natmanager#19]
The `CRAN` build is failing for `natmanager` v0.4.8 (see below):
https://www.stats.ox.ac.uk/pub/bdr/donttest/natmanager.out

The primary cause is that tests marked with `\donttest` in examples seem to run on `CRAN` triggering an error due to GitHub API error (rate limiting issue) as there is no `GITHUB_PAT` set in the `CRAN` environment.

A similar issue has been noted here:
1) https://github.com/r-lib/devtools/issues/2216
2) https://github.com/dankelley/oce/issues/1798

Primarily the solution seems to involve changing the `\donttest` in examples that use the GitHub API to `\dontrun`
See here: https://github.com/r-lib/devtools/issues/2216#issuecomment-805737904

**Comment by jefferis** [comment]
Thanks, Sri! Yes donttest runs on CRAN. Don’t ask! Could you change to dontrun?

**Comment by SridharJagannathan** [comment]
Updated https://github.com/natverse/natmanager/commit/50856f603a859bc72587b29e58cac3cd97326250 after another set of comments from Uwe Ligges

**Comment by SridharJagannathan** [comment]
@jefferis 
* closed via https://github.com/natverse/natmanager/compare/61f358f..8cc0442
* version 0.4.9 now live in CRAN

**Comment by jefferis** [comment]
Hurrah! Thanks so much, Greg.
