### ISSUE TITLE
New CRAN release

### ISSUE THREAD

**Issue by jefferis** [natverse/natmanager#9]
@SridharJagannathan any blockers for release do you think?

**Comment by SridharJagannathan** [comment]
Tasks to be completed:

- [ ] Add example for installing non-natverse packages in`README.md`
- [ ] bump minor version number
- [ ] Version number, downloads in`README.md`
- [ ] update news.md and tag them onto release notes with release version

**Comment by SridharJagannathan** [comment]
@jefferis All done now, I will go ahead and put the version onto `CRAN`

**Comment by jefferis** [comment]
Great! Prob good to test on winbuilder pre CRAN.

**Comment by SridharJagannathan** [comment]
Used `rhub` for build check and uploaded the logs as well, hope the version is approved by `CRAN` soon
